### PR TITLE
Restructure extension and resolve issues with setup scripts/order cancellation

### PR DESCRIPTION
**Pull request by arollason**
This pull request includes two commits. The first commit restructures the extension to match a standard Magento extension structure. This then allows for the extension to be installed with modman or composer, rather than needing to manually copy the files in by hand.

The other commit includes functionality updates:
1. Fix the upgrade/install scripts to work correctly. These were set up incorrectly, and would result in the upgrade scripts being run multiple times. New users on the 0.13.0 version would not have been able to get the extension working at all.
2. Fix a bug with order cancellation. The extension can cancel an order not related to afterpay when using the new version. Adding an API version check prevents this.

Let me know if any changes are required.

### CODE REVIEW

**Comment by bencorlett** [comment]
This looks great! /me following.

**Review by stevenocta — APPROVED** [review]
Token equal signs is a typo and a bug, even if it is not affecting the plugin flow.

The JSON Encode can also help debugging

**Review by stevenocta — COMMENTED** [review]
Hi, thank you for submitting this.

I agree that the 0.13.0 installer is inadequate. I will merge these changes.
The cancel action is also correct.

But, we will need the update scripts because a lot of our merchants are on different versions. 

We experienced update failure from version 0.12.5 for example, because the script used to only cater for updates from 0.12.4 to 0.13.0

Can you please re-add the update scripts that has been deleted and then we will merge the changes

**Review by stevenocta — COMMENTED** [review]
I agree that the structure must be changed since we are not using the main/php/... anyway

We will do it once the merge from the other pull requests are resolved.

I think I will do it separately from this pull request, but I agree that this pull request can be considered approved.

**Review by stevenocta — APPROVED** [review]

**Comment by arollason** [comment]
> We experienced update failure from version 0.12.5 for example, 
> because the script used to only cater for updates from 0.12.4 to 0.13.0

Magento runs a database upgrade for each module that requires it when initialising its configuration. It will take the version from the core_resouce table in the database (eg: 0.12.6) and compare it to the current version in the config file (eg: 0.13.0), find all setup scripts that have a version range between those two, and then run them.

Using these two versions as an example:

DB Version: 0.12.6
Config Version: 0.13.0

If I have a setup script named upgrade-0.12.9-0.13.0.php it will be run when upgrading from 0.12.6 to 0.13.0. This means by maintaining the 0.12.9-0.13.0 script we maintain compatability when upgrading from any version from 0.12.4 and onwards.

The issue I had with the duplicated scripts is that they would ALL be run when doing that upgrade. For example:

DB Version: 0.12.6
Config Version: 0.13.0

Scripts: 
- upgrade-0.12.6-0.13.0.php
- upgrade-0.12.9-0.13.0.php

When the upgrade to 0.13.0 is run while initialising the configuration, Magento will run both of the upgrade scripts. In this case the scripts were identical. Fortunately the functions called in the scripts have checks built in to make running them multiple times safe (the second run will effectively do nothing), however they should still be cleaned up.

Leaving all of the scripts in will just lead to confusion in the future, especially for developers who are not familiar with the Magento setup scripts process. Removing the scripts I chose to remove and maintaining the 0.12.9-0.13.0 script only means that the new columns in the sales quote payment table will absolutely be created whenver a user installs this version of the extension, whether they upgrade from 0.12.4, or 0.12.9 it won't matter.

The following are some examples of this process in action taken from the Magento core codebase:

https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/Resource/Setup.php#L301
https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/Resource/Setup.php#L437
https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/Resource/Setup.php#L600
https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/Resource/Setup.php#L478
https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Core/Model/Resource/Setup.php#L664

As you can see Magento compiles a list of all setup scripts, iterates through them and selects those that fit within the version change. So having the two scripts above and upgrading from 0.12.6-0.13.0 will absolutely result in both of them being run. Retaining just 0.12.9-0.13.0 and removing the rest of the scripts is the correct way to go about resolving this issue.

**Comment by arollason** [comment]
I have rebased the branch on top of the new changes that were pushed since this pull request was started to address the following:
- Resolve any conflicts
- Revert a change to the README which was made as part of the extension restructure. Please see commit https://github.com/afterpay/afterpay-magento/pull/5/commits/fb77cf1aaacbfe72f5ed48499d9a3188100dee65 for more details on this change.
- Updating the version of the extension to 1.0.0 (hopefully not contentious)

I noticed you are using tags that aren't compatible with composer like 0.13.0j. Ideally, you would release this extension on packagist so it can be included using composer without needing to add any specific repository references to the composer.json file of the project you are working in. Details of versioning schemes supported by composer can be found here:

https://getcomposer.org/doc/articles/versions.md
https://github.com/composer/semver/blob/master/src/VersionParser.php#L101

I would suggest continuing to use semver from here on out to make the extension as easy to maintain as possible. Once you have merged this pull request you should tag 1.0.0 (no v prefix) and then add the package to packagist:

https://packagist.org/about

**Pull request merged**
